FROM arm64v8/ubuntu:20.04

ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
 && apt-get install -y sudo \
 && apt-get install -y avahi-daemon \
 && apt-get install -y git

RUN adduser --disabled-password --gecos '' wirepod \
 && adduser wirepod sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER wirepod

RUN mkdir /home/wirepod/wire-pod \
 && cd /home/wirepod/wire-pod \
 && git clone https://github.com/kercre123/wire-pod.git .

WORKDIR /home/wirepod/wire-pod

CMD sudo STT=vosk ./setup.sh && sudo ./chipper/setup.sh && sudo ./chipper/start.sh
